### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined

### ISSUE THREAD

**Issue by gotar** [EU-EDPS/website-evidence-collector#11] opened 2019-10-16 10:50 UTC
For a simple call (and many others) I got

`$ website-evidence-collector --yaml --no-output --quiet https://google.com -- --ignore-certificate-errors`

```
(node:30510) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Object.keys.forEach (/home/gotar/Programowanie/BeLighted/Admeet-API/node_modules/website-evidence-collector/website-evidence-collector.js:295:33)
    at Array.forEach (<anonymous>)
    at /home/gotar/Programowanie/BeLighted/Admeet-API/node_modules/website-evidence-collector/website-evidence-collector.js:294:29
    at <anonymous>
(node:30510) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30510) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rriemann-eu** [comment] 2019-10-16 11:50
I remember I have worked on this issue in https://github.com/EU-EDPS/website-evidence-collector/commit/d3939e14e4dd65cfc4403baf0f96aca1b01769a2 . I cannot reproduce your issue with the current master version.

Can you please try with the current master version and report back?

**Comment by gotar** [comment] 2019-10-16 11:55
```
$ cat yarn.lock | grep website-evidence-collector
"website-evidence-collector@https://github.com/EU-EDPS/website-evidence-collector/tarball/master":
  resolved "https://github.com/EU-EDPS/website-evidence-collector/tarball/master#2449f445e8480e3e8c449f00f2e9a9f46771a924"
```

```
$  ./node_modules/.bin/website-evidence-collector --yaml --no-output --quiet https://google.com -- --ignore-certificate-errors

 data: 
   [ { key: 'CONSENT',
       value: 'WP.27f557',
       expires: '2038-01-01T00:00:00.000Z',
       domain: 'google.com',
       path: '/',
       creation: '2019-10-16T11:52:56.507Z' } ],
  level: 'warn',
  message: '1 Cookie(s) (HTTP) set for host google.com with key(s) CONSENT.',
  timestamp: '2019-10-16T11:52:56.508Z' }
{ type: 'Browser',
  level: 'info',
  message: 'browsing now to https://google.com',
  timestamp: '2019-10-16T11:52:56.149Z' }
(node:20117) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Object.keys.forEach (/home/gotar/Programowanie/BeLighted/Admeet-API/node_modules/website-evidence-collector/website-evidence-collector.js:295:33)
    at Array.forEach (<anonymous>)
    at /home/gotar/Programowanie/BeLighted/Admeet-API/node_modules/website-evidence-collector/website-evidence-collector.js:294:29
    at <anonymous>
(node:20117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
$ echo $?
0
```

**Comment by kkenderesi** [comment] 2019-10-16 13:32
I have the same issue but just with some URLs. I can PM you one to test.

**Comment by rriemann-eu** [comment] 2019-10-16 13:41
@gotar I do not know where the yarn.lock comes from. We cannot support any other setups than our own. I have again downloaded the tool and did not experience a problem. If `2449f445e8480e3e8c449f00f2e9a9f46771a924` in `"https://github.com/EU-EDPS/website-evidence-collector/tarball/master#2449f445e8480e3e8c449f00f2e9a9f46771a924"` is a commit number, I could not find it. [Check here](https://github.com/EU-EDPS/website-evidence-collector/commit/2449f445e8480e3e8c449f00f2e9a9f46771a924).

Can you please provide a minimal non-working example to demonstrate the issue that includes both the setup and the run of the tool.

@kkenderesi Can you tell me if you have installed the testing version as of yesterday evening or the latest released version? The readme explains how to choose during installation. https://edps.europa.eu/press-publications/edps-inspection-software_en has a mail address for non-public input.

**Comment by kkenderesi** [comment] 2019-10-16 13:50
@rriemann-eu I have the version ## 0.3.0 / 2019-09-25 installed approx 1.5 weeks ago. I am using Ubuntu 19.04, NodeJS v8.16.1 and NPM 6.4.1. It is definitely not the testing version.

**Comment by kkenderesi** [comment] 2019-10-16 14:07
@rriemann-eu This is what I get when testing google.com:

...@ubuntu:~$ website-evidence-collector --output ./output/google https://google.com | pino-pretty --timestampKey timestamp --messageKey type --ignore stack,raw,origin >> ./output/google.txt

(node:2467) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at Object.keys.forEach (/usr/lib/node_modules/website-evidence-collector/website-evidence-collector.js:295:33)
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/website-evidence-collector/website-evidence-collector.js:294:29
    at <anonymous>
(node:2467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rriemann-eu** [comment] 2019-10-17 08:12
With the most recent changes, I cannot reproduce this bug anymore. The next release 0.3.1 to be published this or next week will have these changes integrated. So I close this issue. It can be reopened if there is evidence that the recent changes are insufficient.

**Closed by rriemann-eu** 2019-10-17 08:12 UTC
Labels: bug

**Comment by gotar** [comment] 2019-10-17 08:43
Hmm I just checked current master, still exists. But can wait till 0.3.1 to retest again. Maybe it's some 3rd party stuff like node version, or dependency

**Comment by rriemann-eu** [comment] 2019-10-17 08:54
The last error message was helpful. I just added one more change.
