### ISSUE TITLE
HTML table improper formating

### ISSUE THREAD

**Issue by cderp** [EU-EDPS/website-evidence-collector#79] opened 2022-08-16 10:47 UTC
Some of the tables in the "inspection.html" document are displaying incorrectly in the Firefox browser. In the cookie tables, the "name" column is shrunk down to nothing and in the local storage table, all columns are.

After some digging the problem appears to be that in the .trunc style (assets/template.pug), the maxwidth was set to 1px. For some reason that works in Chrome but doesn't work in Firefox, where the column is instead always shrunk to (almost) nothing, making it basically unreadable. Setting the maxwidth to 100% fixed the issue for me.

**Comment by rriemann** [comment] 2022-08-21 17:28
Thank you for the report. Can you prepare a pull request or post here a code snippet? Have you tested our fix in both Firefox and Chrome?

**Comment by atjn** [comment] 2022-08-28 13:03
This has already been fixed in https://github.com/EU-EDPS/website-evidence-collector/commit/c0707d2beba832d32f171048276dc2d5b2b9bdfa, but it hasn't been released yet. There are actually many regressions in `v2.0.0` that was fixed two months ago, but that haven't been released yet. Is there any reason why you haven't released a `v2.0.1` that fixes these?

Some examples of other fixes that haven't been released yet:
https://github.com/EU-EDPS/website-evidence-collector/commit/b889f8c85fb505cf25378bde187a394503fe336c
https://github.com/EU-EDPS/website-evidence-collector/commit/8d93d71f0da998d9bae176672ecea3cb326e37aa
https://github.com/EU-EDPS/website-evidence-collector/commit/bd3f2145dc68f8a1228c74c03e4220cca57095e0

I am running my own custom version of WEC 2.0 right now because it is unusable for me without some of the fixes.

**Comment by rriemann** [comment] 2022-08-31 06:56
Dear @atjn, the services have been in summer holidays in between and we have no manpower for better release management. The plan is to release the current master soon as 2.1 or 3.0. Anyway, I understand that this is urgent and give priority to publishing a new release. For those who cannot wait, I propose to try the master branch.

**Closed by rriemann** 2022-08-31 06:56 UTC
