### ISSUE TITLE
Install Fails because of Puppeteer

### ISSUE THREAD

**Issue by sphinxsm** [EU-EDPS/website-evidence-collector#8] opened 2019-10-13 13:52 UTC
Hi

I have tried installing on my Mac, on a Virtual Linux machine and on a windows machine and get errors.

I am trying to get it to work on my Mac and keep getting an error on Puppeteer install. I get this:

> <<<<
> 
> > puppeteer@1.20.0 install /usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer
> > node install.js
> 
> ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
> Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/website-evidence-collector/node_modules/puppeteer/.local-chromium'
> 
> 
> >>>>>

I successfully installed Puppeteer separately and did not get any errors. Was hoping by installing Puppeteer first it would skip install as WEC saw I had latest version but no luck. 

I am not that good with the terminal so any help would be appreciated to resolve this issue, i.e. maybe the SKIP_CHROMIUM_DOWNLOAD might be a way forward but no idea how to do this.

Thanks,
Sean

**Comment by rriemann-eu** [comment] 2019-10-13 14:30
Thank you for your interest. This issue is a duplicate of #5. 

Please consult the new FAQ for a solution.

https://github.com/EU-EDPS/website-evidence-collector/blob/master/FAQ.md#question-why-does-the-installation-with-npm-install-fail-with-permision-denied

**Closed by rriemann-eu** 2019-10-13 14:30 UTC
